@startuml
title Diagrama de Classes – Sistema de agendamento 
left to right direction

' Classes principais
class Clientes {
    - usuario: String
    - nome: String
    + realizarAgendamento(d: profissional): String
}

class Profissional{
    - usuario: String
    - nome: String
    - servico: int
    - dataDispon: int
    - horariosDispon: float
    + verificarDisponibilidade(): bool
}

class Agendar{
    - dataDispon: int
    - horarioDispon: float
    - status: String
    - cliente: Cliente
    - profissional: Profissional
}

' Relações estruturais
Agendar"*" --> "1" Clientes: cliente
Agendar"*" --> "1" Profissional: profissional
@enduml
