@startuml
left to right direction

actor Cliente
actor Profissional
rectangle "Spafy"{
usecase "Realizar login" as UC1
usecase "Cadasrar cliente" as UC2
usecase "Pesquisar servicos disponiveis" as UC3
usecase "Agendar servico" as UC4
usecase "Avaliar Profissional" as UC5
usecase "Cadastrar Profissional" as UC6
usecase "Verificar Agenda" as UC7
usecase "Realizar saque" as UC8
usecase "Avliar cliente" as UC9
usecase "Editar perfil" as UC10
}
Cliente --> UC1
Cliente --> UC2
Cliente --> UC3
Cliente --> UC4
Cliente --> UC5

Profissional --> UC1
Profissional --> UC7
Profissional --> UC8
Profissional --> UC9
Profissional --> UC10
@enduml
